#!/bin/bash

git pull

username="YOURNAME"

homedir=`pwd`
if [ ! -d "$homedir/../moodle" ]; then

    git clone git@github.com:$username/moodle.git ../moodle

    pushd $homedir/../moodle
    git remote add upstream https://github.com/moodle/moodle.git
    git fetch upstream
    git submodule update --recursive --init
    popd
fi


vagrant box update

echo "Starting the VM"
vagrant up
