#!/bin/bash

git pull

if [ -z "$(vagrant plugin list | grep vagrant-hosts)" ]; then
    vagrant plugin install vagrant-hosts
fi

username="YOURNAME"

homedir=`pwd`
if [ ! -d "$homedir/../moodle" ]; then
    if curl --output /dev/null --silent --head --fail "https://github.com/$username/moodle"
    then
        echo $username"/moodle exists, cloning"
        git clone git@github.com:$username/moodle.git ../moodle

        pushd $homedir/../moodle
        git remote add upstream https://github.com/moodle/moodle.git
        git fetch upstream
        git submodule update --recursive --init
        popd
    else
        echo $username"/moodle does not exists, cloning official"
        git clone git@github.com:moodle/moodle.git ../moodle
    fi
fi

if [ ! -d "$homedir/../moodlemobile2" ]; then
    if curl --output /dev/null --silent --head --fail "https://github.com/$username/moodlemobile2"
    then
        echo $username"/moodlemobile2 exists, cloning"
        git clone git@github.com:$username/moodlemobile2.git ../moodlemobile2

        pushd $homedir/../moodlemobile2
        git remote add upstream https://github.com/moodlehq/moodlemobile2.git
        git fetch upstream
        git submodule update --recursive --init
        popd
    else
        echo $username"/moodlemobile2 does not exists, cloning official"
        git clone git@github.com:moodlehq/moodlemobile2.git ../moodlemobile2
    fi
fi

vagrant box update

echo "Starting the VM..."
vagrant up
echo "VM started!"

if [ -n "$1" ]; then
	echo "Running Ionic..."
	vagrant ssh -c "/vagrant/provision/ionicinit.sh"
else
	echo "Not running Ionic"
	echo "Execute vagrant ssh -c /vagrant/provision/ionicinit.sh"
fi
